name: fetch3-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - pytest
    - snakeviz
    - black
    - isort
    - flakeheaven
    - m2r2
    - sphinx>=4.4,<6  # <6 b/c pydata (<=0.12) doesn't work with sphinx 6
    - pydata-sphinx-theme<0.12.0  # pydata 0.12 has a flyout menu bug